version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fund_mgt_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run flask run --host=0.0.0.0
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      SQLITE_DATABASE_URL: sqlite:///fund_mgt_development.db
      MYSQL_DATABASE_URL: mysql+pymysql://user:password@db:3306/fund_mgt_development
    volumes:
      - .:/aham

volumes:
  db-data:
